"use server";

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

const MAX_LISTINGS_PER_HOUR = 10;
const RATE_LIMIT_ERROR_MESSAGE = "You can post up to 10 listings per hour. Please wait before posting again.";

const uploadedImageSchema = z.object({
  objectKey: z.string().min(1),
  publicUrl: z.string().url(),
});

/** The listing content itself. Validated when the draft is created, before any upload. */
const listingContentSchema = z.object({
  title: z.string().min(3).max(100),
  description: z.string().min(10).max(2000),
  price: z.coerce.number().positive().max(999999),
  categoryId: z.string().uuid("Invalid category"),
  universityId: z.string().uuid("Invalid university"),
  condition: z.enum(["new", "like_new", "good", "fair"]).optional(),
  isService: z.coerce.boolean().default(false),
});

// Publishing re-validates the content as well as the images. The client reuses its
// draft when a submit fails partway (so a retry does not strand a second row), which
// means the row can be older than what the user is looking at — if they fixed a field
// and resubmitted, the draft still holds the original value. Writing the content again
// here is what keeps the published listing equal to the form that was submitted.
const publishSchema = listingContentSchema.extend({
  listingId: z.string().uuid("Invalid listing id"),
  uploadedImages: z.array(uploadedImageSchema).max(6),
});

export type CreateListingState = {
  errors?: Partial<Record<string, string[]>>;
  message?: string;
};

export type CreateDraftState = CreateListingState & { listingId?: string };

function readContent(formData: FormData) {
  return {
    title: formData.get("title"),
    description: formData.get("description"),
    price: formData.get("price"),
    categoryId: formData.get("categoryId"),
    universityId: formData.get("universityId"),
    condition: formData.get("condition") || undefined,
    isService: formData.get("isService") === "true",
  };
}

/**
 * Step 1 of posting: validate everything and reserve a `draft` listing row.
 *
 * This exists so authorization happens BEFORE any bytes are uploaded. The old flow
 * minted a listing id in the browser, uploaded every image, and only then checked
 * `is_verified_student` — so a rejected user had already filled the bucket, and
 * nothing cleaned up after them (the compensating delete only fired on insert
 * failure, not on the early returns).
 *
 * It also gives the presign endpoint a real row to check ownership against, instead
 * of a client-supplied id it would have to trust.
 *
 * Drafts are invisible: `listings_public_read` requires `status = 'active'`, so an
 * abandoned draft appears in no feed. The reaper clears them after 24h.
 */
export async function createDraftListingAction(formData: FormData): Promise<CreateDraftState> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return { message: "You must be signed in to post a listing." };
  }

  const { data: profile, error: profileError } = await supabase
    .from("profiles")
    .select("is_verified_student")
    .eq("id", user.id)
    .maybeSingle();

  if (profileError) {
    return { message: `We could not confirm your seller permissions: ${profileError.message}` };
  }

  if (!profile?.is_verified_student) {
    return {
      message:
        "Only verified students can create listings on CampusCart. Verify or link your student account before selling.",
    };
  }

  const parsed = listingContentSchema.safeParse(readContent(formData));
  if (!parsed.success) {
    return { errors: parsed.error.flatten().fieldErrors };
  }

  // Drafts are excluded from this count — an abandoned sell form should never
  // consume someone's hourly allowance. The DB policy enforces the same rule.
  const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000).toISOString();
  const { count: recentCount, error: rateLimitError } = await supabase
    .from("listings")
    .select("id", { count: "exact", head: true })
    .eq("seller_id", user.id)
    .neq("status", "draft")
    .gte("created_at", oneHourAgo);

  if (rateLimitError) {
    return { message: rateLimitError.message };
  }

  if ((recentCount ?? 0) >= MAX_LISTINGS_PER_HOUR) {
    return { message: RATE_LIMIT_ERROR_MESSAGE };
  }

  // The id is generated by the database, not the client — the browser no longer has
  // a say in which key namespace its uploads land in.
  const { data: listing, error: draftError } = await supabase
    .from("listings")
    .insert({
      seller_id: user.id,
      title: parsed.data.title,
      description: parsed.data.description,
      price: parsed.data.price,
      category_id: parsed.data.categoryId,
      university_id: parsed.data.universityId,
      condition: parsed.data.condition ?? null,
      is_service: parsed.data.isService,
      status: "draft",
    })
    .select("id")
    .single();

  if (draftError) {
    if (draftError.message.toLowerCase().includes("row-level security")) {
      return { message: RATE_LIMIT_ERROR_MESSAGE };
    }
    return { message: `Failed to start listing: ${draftError.message}` };
  }

  return { listingId: listing.id };
}

/**
 * Step 2: attach the uploaded images and publish. The row already exists as a draft,
 * so this flips status rather than inserting.
 */
export async function createListingAction(
  _prevState: CreateListingState,
  formData: FormData
): Promise<CreateListingState> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return { message: "You must be signed in to post a listing." };
  }

  const parsed = publishSchema.safeParse({
    ...readContent(formData),
    listingId: formData.get("listingId"),
    uploadedImages: (() => {
      const rawValue = formData.get("uploadedImages");
      if (typeof rawValue !== "string") {
        return [];
      }

      try {
        const parsedImages = JSON.parse(rawValue);
        return Array.isArray(parsedImages) ? parsedImages : [];
      } catch (e) {
        console.error("[ERROR] Failed to parse uploadedImages JSON:", e);
        return [];
      }
    })(),
  });

  if (!parsed.success) {
    return { errors: parsed.error.flatten().fieldErrors };
  }
  const { listingId, uploadedImages, ...content } = parsed.data;

  // Ownership and state. Publishing something that is not your own draft is not a
  // thing that should ever happen, so it is a flat refusal rather than a repair.
  const { data: draft, error: draftLookupError } = await supabase
    .from("listings")
    .select("id, seller_id, status")
    .eq("id", listingId)
    .maybeSingle();

  if (draftLookupError) {
    return { message: `Failed to publish listing: ${draftLookupError.message}` };
  }
  if (!draft || draft.seller_id !== user.id) {
    return { message: "That listing could not be found." };
  }
  if (draft.status !== "draft") {
    return { message: "That listing has already been published." };
  }

  // Images first: a published listing with no photos is worse than a draft that
  // failed to publish, and the draft is retryable.
  if (uploadedImages.length > 0) {
    // Dual write, on purpose. object_key is what new clients read; public_url is
    // still populated (with the CDN URL) because APKs already in the wild select only
    // public_url and cannot be force-updated. Costs one text column and keeps old
    // installs rendering the new images. See R2_MIGRATION_PLAN.md section 5.6.
    const imagesToInsert = uploadedImages.map((image, index) => ({
      listing_id: listingId,
      object_key: image.objectKey,
      public_url: image.publicUrl,
      sort_order: index,
    }));

    const { error: imageInsertError } = await supabase
      .from("listing_images")
      .insert(imagesToInsert)
      .select();

    if (imageInsertError) {
      console.error("[ERROR] Image insert failed:", imageInsertError);
      return { message: `Images could not be saved: ${imageInsertError.message}` };
    }
  }

  const { error: publishError } = await supabase
    .from("listings")
    .update({
      title: content.title,
      description: content.description,
      price: content.price,
      category_id: content.categoryId,
      university_id: content.universityId,
      condition: content.condition ?? null,
      is_service: content.isService,
      status: "active",
    })
    .eq("id", listingId)
    .eq("seller_id", user.id);

  if (publishError) {
    return { message: `Failed to publish listing: ${publishError.message}` };
  }

  revalidatePath("/");
  revalidatePath("/browse");
  redirect(`/product/${listingId}`);
}
