import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#020817',
  card: '#0f172a',
  border: '#1e293b',
  text: '#f8fafc',
  muted: '#94a3b8',
  dim: '#64748b',
  primary: '#0ea5e9',
  secondary: '#f59e0b',
  success: '#10b981',
  accent: '#a78bfa',
  danger: '#ef4444',
  white: '#ffffff',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.bg },
  container: { flex: 1, backgroundColor: colors.bg },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingCard: {
    width: '84%',
    maxWidth: 320,
    backgroundColor: 'rgba(30, 41, 59, 0.56)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.24)',
    paddingHorizontal: 18,
    paddingVertical: 20,
    alignItems: 'center',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  loadingCartWrap: {
    padding: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(15, 23, 42, 0.62)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.35)',
  },
  loadingTrack: {
    width: 120,
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(148, 163, 184, 0.24)',
    overflow: 'hidden',
  },
  loadingTrackGlow: {
    width: 30,
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(245, 158, 11, 0.95)',
  },
  loadingText: { color: '#cbd5e1', fontSize: 16 },
  authToastContainer: {
    position: 'absolute',
    top: 16,
    left: 16,
    right: 16,
    alignItems: 'center',
    zIndex: 40,
  },
  authToastCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    maxWidth: 360,
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.45)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  authToastCopy: { flex: 1 },
  authToastTitle: { color: colors.text, fontSize: 13, fontWeight: '800' },
  authToastBody: { color: '#cbd5e1', fontSize: 12, marginTop: 1 },
  feedbackModalBackdrop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(2, 8, 23, 0.74)',
    paddingHorizontal: 22,
  },
  feedbackModalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#0b1220',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    paddingHorizontal: 18,
    paddingVertical: 20,
    alignItems: 'center',
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 12,
    elevation: 6,
  },
  feedbackModalIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(245, 158, 11, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.4)',
  },
  feedbackModalTitle: { color: colors.text, fontSize: 18, fontWeight: '900', textAlign: 'center' },
  feedbackModalMessage: { color: '#cbd5e1', fontSize: 14, lineHeight: 21, textAlign: 'center' },
  feedbackModalButton: {
    marginTop: 6,
    width: '100%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.45)',
    backgroundColor: 'rgba(245, 158, 11, 0.16)',
    paddingVertical: 12,
    alignItems: 'center',
  },
  feedbackModalButtonText: { color: colors.secondary, fontSize: 14, fontWeight: '800' },
  headerBrand: { color: colors.text, fontSize: 24, fontWeight: '800' },
  headerSubtitle: { color: colors.muted, fontSize: 12 },
  screenContent: { paddingHorizontal: 18, paddingBottom: 120, paddingTop: 16, gap: 14 },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', gap: 12 },
  sectionHeaderCopy: { flex: 1, gap: 4 },
  sectionEyebrow: { color: colors.accent, textTransform: 'uppercase', letterSpacing: 1.2, fontWeight: '800', fontSize: 11 },
  sectionBody: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  sectionBadge: { backgroundColor: 'rgba(167, 139, 250, 0.15)', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: colors.accent },
  sectionBadgeText: { color: colors.accent, fontWeight: '800', fontSize: 11, textTransform: 'uppercase' },
  heroCard: { backgroundColor: colors.card, borderRadius: 28, padding: 22, borderWidth: 1, borderColor: colors.border, gap: 12 },
  heroCardCompact: { backgroundColor: colors.card, borderRadius: 24, paddingHorizontal: 18, paddingVertical: 16, borderWidth: 1, borderColor: colors.border, gap: 10 },
  heroBrandRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 2 },
  heroLogo: { width: 34, height: 34, borderRadius: 8, backgroundColor: '#111827' },
  heroBrandTitle: { color: colors.text, fontWeight: '900', fontSize: 16 },
  heroBrandSubtitle: { color: colors.muted, fontSize: 11, marginTop: 1 },
  heroEyebrow: { color: colors.accent, textTransform: 'uppercase', letterSpacing: 1, fontWeight: '800', fontSize: 12 },
  heroTitle: { color: colors.text, fontSize: 30, fontWeight: '900', lineHeight: 36 },
  heroBody: { color: '#cbd5e1', fontSize: 15, lineHeight: 22 },
  heroButtonRow: { flexDirection: 'row', gap: 10, marginTop: 8 },
  statsRow: { flexDirection: 'row', gap: 10, marginTop: 10 },
  statCard: { flex: 1, backgroundColor: '#081120', borderRadius: 18, borderWidth: 1, borderColor: '#1e293b', padding: 14, gap: 4 },
  statValue: { color: colors.text, fontWeight: '900', fontSize: 20 },
  statLabel: { color: colors.muted, fontSize: 12 },
  primaryButton: { backgroundColor: colors.primary, paddingHorizontal: 18, paddingVertical: 14, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  primaryButtonText: { color: colors.white, fontWeight: '800', fontSize: 15 },
  secondaryButton: { backgroundColor: 'rgba(245, 158, 11, 0.15)', borderWidth: 1.5, borderColor: colors.secondary, paddingHorizontal: 18, paddingVertical: 14, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  secondaryButtonText: { color: colors.secondary, fontWeight: '800', fontSize: 15 },
  sectionTitle: { color: colors.text, fontWeight: '800', fontSize: 22, marginTop: 8 },
  horizontalStrip: { marginTop: 4 },
  homeCategoryChip: {
    backgroundColor: colors.card,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 9,
    paddingVertical: 6,
    marginRight: 8,
  },
  homeCategoryChipText: { color: '#cbd5e1', fontWeight: '700', fontSize: 11 },
  filterStripContent: { paddingRight: 8 },
  browseHeaderSection: { gap: 10, marginBottom: 8 },
  browseListContent: { paddingBottom: 120, gap: 12 },
  browseGridRow: { gap: 10, marginBottom: 10 },
  browseGridItem: { flex: 1 },
  chip: { backgroundColor: colors.card, borderRadius: 999, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, paddingVertical: 10, marginRight: 8 },
  chipActive: { backgroundColor: colors.secondary, borderColor: colors.secondary },
  chipText: { color: '#cbd5e1', fontWeight: '700', fontSize: 13 },
  chipTextActive: { color: '#000000', fontWeight: '800' },
  favoriteButton: { width: 42, height: 42, borderRadius: 999, backgroundColor: 'rgba(2, 8, 23, 0.82)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#334155' },
  favoriteButtonActive: { backgroundColor: '#7f1d1d', borderColor: '#ef4444' },
  favoriteButtonText: { color: colors.white, fontSize: 18 },
  input: { backgroundColor: colors.card, borderRadius: 18, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 16, paddingVertical: 14, color: colors.text, fontSize: 15 },
  multilineInput: { minHeight: 110, textAlignVertical: 'top' },
  card: { backgroundColor: colors.card, borderRadius: 24, overflow: 'hidden', borderWidth: 1, borderColor: colors.border, marginTop: 12 },
  cardCompact: { marginTop: 0, borderRadius: 18 },
  cardHomeTight: { borderRadius: 16 },
  cardImage: { width: '100%', height: 228, backgroundColor: '#111827' },
  cardImageCompact: { height: 164 },
  cardImageHomeTight: { height: 196 },
  cardImageWrap: { position: 'relative' },
  imageCountBadge: { position: 'absolute', right: 12, bottom: 12, backgroundColor: 'rgba(2, 8, 23, 0.82)', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: '#334155' },
  cardTopActions: { position: 'absolute', top: 12, right: 12, flexDirection: 'row', gap: 8 },
  cardImageMessageButton: {
    position: 'absolute',
    left: 12,
    bottom: 12,
    backgroundColor: 'rgba(2, 8, 23, 0.72)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.22)',
  },
  cardImageMessageButtonText: { color: colors.white, fontSize: 11, fontWeight: '800' },
  imageCountBadgeText: { color: colors.white, fontWeight: '700', fontSize: 12 },
  cardContent: { paddingHorizontal: 11, paddingTop: 10, paddingBottom: 11, gap: 5 },
  cardContentHomeTight: { paddingHorizontal: 7, paddingTop: 6, paddingBottom: 6, gap: 2 },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  cardCategory: { color: colors.success, fontWeight: '800', fontSize: 12 },
  cardConditionLabel: {
    color: '#d1fae5',
    fontWeight: '800',
    fontSize: 11,
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.45)',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  trustRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  trustRowCompact: { marginTop: 2, gap: 6 },
  trustRowHomeTight: { marginTop: 1, gap: 5 },
  trustPill: { backgroundColor: 'rgba(16, 185, 129, 0.12)', borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.3)', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  trustPillText: { color: colors.success, fontSize: 11, fontWeight: '700' },
  trustPillHomeTight: { paddingHorizontal: 8, paddingVertical: 4 },
  trustPillTextHomeTight: { fontSize: 10 },
  cardPrice: { color: colors.text, fontWeight: '900', fontSize: 15 },
  cardPriceCompact: { fontSize: 12 },
  cardPriceHomeTight: { fontSize: 13 },
  cardTitle: { color: colors.text, fontWeight: '800', fontSize: 16 },
  cardTitleCompact: { fontSize: 12, lineHeight: 15 },
  cardTitleHomeTight: { fontSize: 12, lineHeight: 14 },
  cardMeta: { color: colors.muted, fontSize: 13 },
  cardMetaHomeTight: { fontSize: 11 },
  cardMetaLine: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  cardMetaLineLeft: { flexDirection: 'row', alignItems: 'center', gap: 6, flex: 1 },
  cardDescription: { color: '#cbd5e1', fontSize: 14, lineHeight: 20 },
  cardSeller: { color: '#e2e8f0', fontWeight: '700', fontSize: 11 },
  cardSellerHomeTight: { fontSize: 10 },
  cardVerifiedBadge: {
    width: 20,
    height: 20,
    borderRadius: 999,
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardVerifiedBadgeText: { color: '#34d399', fontSize: 12, fontWeight: '900' },
  cardSellerAvatar: { width: 24, height: 24, borderRadius: 12, marginRight: 6 },
  cardDate: { color: colors.dim, fontSize: 10 },
  cardDateHomeTight: { fontSize: 9 },
  cardFooterCompact: { marginTop: 2 },
  detailImage: { width: '100%', height: 260, borderRadius: 26, backgroundColor: '#111827' },
  detailThumbRow: { marginTop: 12 },
  detailThumb: { width: 78, height: 78, borderRadius: 16, marginRight: 10, borderWidth: 1, borderColor: '#1e293b', backgroundColor: '#111827' },
  detailCategory: { color: colors.success, fontWeight: '800', fontSize: 13, marginTop: 16 },
  detailTitle: { color: colors.text, fontWeight: '900', fontSize: 28, lineHeight: 34, marginTop: 8 },
  detailPrice: { color: colors.text, fontWeight: '900', fontSize: 24, marginTop: 8 },
  detailMeta: { color: colors.muted, marginTop: 6, fontSize: 14 },
  detailBody: { color: '#cbd5e1', marginTop: 14, fontSize: 15, lineHeight: 22 },
  detailMetaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 12 },
  detailMetaPill: { backgroundColor: '#081120', borderRadius: 999, borderWidth: 1, borderColor: '#1e293b', paddingHorizontal: 12, paddingVertical: 8 },
  detailMetaPillText: { color: '#cbd5e1', fontWeight: '700', fontSize: 12 },
  detailInfoCard: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 22, padding: 18, marginTop: 18, gap: 4 },
  infoLabel: { color: colors.dim, textTransform: 'uppercase', fontSize: 11, fontWeight: '800', marginTop: 10 },
  infoValue: { color: colors.text, fontSize: 15 },
  noticeCard: { backgroundColor: colors.card, borderRadius: 24, borderWidth: 1, borderColor: '#334155', padding: 18, marginTop: 8 },
  noticeTitle: { color: colors.text, fontWeight: '800', fontSize: 18 },
  noticeBody: { color: '#cbd5e1', lineHeight: 22, marginTop: 8 },
  fieldLabel: { color: '#cbd5e1', fontWeight: '700', marginTop: 6 },
  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  categoryChoice: { backgroundColor: colors.card, borderRadius: 16, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, paddingVertical: 12 },
  categoryChoiceActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  categoryChoiceText: { color: '#cbd5e1', fontWeight: '700' },
  categoryChoiceTextActive: { color: colors.white },
  // Glassmorphic Profile Card with premium feel
  profileCard: { 
    backgroundColor: 'rgba(30, 41, 59, 0.6)', 
    borderRadius: 32, 
    borderWidth: 1.5, 
    borderColor: 'rgba(148, 163, 184, 0.2)', 
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
  },
  profileTopRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  avatarLarge: { 
    width: 80, 
    height: 80, 
    borderRadius: 999, 
    backgroundColor: '#111827',
    borderWidth: 2,
    borderColor: 'rgba(14, 165, 233, 0.3)',
    shadowColor: '#0ea5e9',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  profileName: { color: colors.text, fontWeight: '800', fontSize: 24, letterSpacing: 0.2 },
  profileMeta: { color: 'rgba(148, 163, 184, 0.8)', marginTop: 6, fontSize: 14 },
  miniStatRow: { flexDirection: 'row', gap: 10, marginTop: 18 },
  miniStatCard: { 
    flex: 1, 
    backgroundColor: 'rgba(15, 23, 42, 0.7)', 
    borderRadius: 20, 
    borderWidth: 1, 
    borderColor: 'rgba(148, 163, 184, 0.15)', 
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  miniStatValue: { color: '#38bdf8', fontWeight: '900', fontSize: 20, letterSpacing: 0.3 },
  miniStatLabel: { color: 'rgba(148, 163, 184, 0.7)', fontSize: 12, marginTop: 4 },
  badgeRow: { flexDirection: 'row', gap: 8, marginTop: 18 },
  badge: { 
    borderRadius: 999, 
    paddingHorizontal: 14, 
    paddingVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  badgeVerified: { 
    backgroundColor: 'rgba(6, 78, 59, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  badgePending: { 
    backgroundColor: 'rgba(63, 63, 70, 0.7)',
    borderWidth: 1,
    borderColor: 'rgba(113, 113, 122, 0.3)',
  },
  badgeText: { color: colors.white, fontWeight: '700', fontSize: 12 },
  unreadDot: { width: 10, height: 10, borderRadius: 999, backgroundColor: colors.secondary },
  switchAuthText: { color: colors.secondary, textAlign: 'center', fontWeight: '700', marginTop: 4 },
  emptyState: { backgroundColor: colors.card, borderRadius: 24, borderWidth: 1, borderColor: colors.border, padding: 22, marginTop: 12 },
  emptyTitle: { color: colors.text, fontWeight: '800', fontSize: 18 },
  emptyBody: { color: colors.muted, marginTop: 6, lineHeight: 20 },
  backButton: { alignSelf: 'flex-start', backgroundColor: colors.card, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 10, borderWidth: 1, borderColor: colors.border },
  backButtonText: { color: '#e2e8f0', fontWeight: '700' },
  imagePreview: { width: 96, height: 96, borderRadius: 16, marginRight: 10, backgroundColor: '#111827' },
  helperText: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  helperCard: { backgroundColor: '#081120', borderRadius: 18, borderWidth: 1, borderColor: '#1e293b', padding: 14, gap: 6 },
  helperCardTitle: { color: colors.text, fontWeight: '800', fontSize: 14 },
  formSection: { gap: 10, marginTop: 6 },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: 6 },
  statusCard: { backgroundColor: '#081120', borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 14, gap: 6 },
  statusTitle: { color: colors.text, fontWeight: '800', fontSize: 15 },
  statusBody: { color: '#cbd5e1', lineHeight: 20, fontSize: 13 },
  sellerListingCard: { backgroundColor: '#081120', borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 14, gap: 8 },
  sellerListingTitle: { color: colors.text, fontWeight: '800', fontSize: 16 },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 6 },
  smallButton: { backgroundColor: '#0f172a', borderRadius: 999, borderWidth: 1, borderColor: '#334155', paddingHorizontal: 12, paddingVertical: 10 },
  smallButtonDanger: { backgroundColor: '#3f0b0b', borderColor: '#7f1d1d' },
  smallButtonText: { color: '#e2e8f0', fontWeight: '700', fontSize: 12 },
  avatarOption: {
    width: 64,
    height: 64,
    borderRadius: 999,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#334155',
    marginRight: 10,
    marginVertical: 6,
  },
  avatarOptionSelected: {
    borderColor: '#38bdf8',
  },
  avatarOptionImage: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#111827',
  },
  
  // Premium profile features
  profileContactButton: { 
    backgroundColor: 'rgba(14, 165, 233, 0.15)',
    borderWidth: 1.5,
    borderColor: 'rgba(14, 165, 233, 0.5)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    shadowColor: '#0ea5e9',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  },
  profileContactButtonText: { 
    color: '#38bdf8', 
    fontWeight: '800', 
    fontSize: 14 
  },
  profileMetricsRow: { 
    flexDirection: 'row', 
    gap: 12, 
    marginTop: 16 
  },
  profileMetricItem: { 
    flex: 1,
    backgroundColor: 'rgba(14, 165, 233, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(14, 165, 233, 0.2)',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  profileMetricLabel: { 
    color: 'rgba(148, 163, 184, 0.8)', 
    fontSize: 11, 
    fontWeight: '700',
    marginTop: 4
  },
  profileMetricValue: { 
    color: '#38bdf8', 
    fontWeight: '900', 
    fontSize: 16 
  },
  profileAboutCard: {
    backgroundColor: 'rgba(30, 41, 59, 0.5)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.15)',
    padding: 14,
    marginTop: 14,
  },
  profileAboutLabel: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  profileAboutText: {
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
  },

  // Home Grid Listing
  homeGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  homeGridItem: {
    flex: 1,
    minWidth: '48%',
  },
  viewMoreButton: {
    marginTop: 14,
    paddingVertical: 14,
    paddingHorizontal: 18,
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    borderWidth: 1.5,
    borderColor: colors.secondary,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewMoreButtonText: {
    color: colors.secondary,
    fontWeight: '800',
    fontSize: 15,
  },
});
