import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#020817',
  card: '#0f172a',
  border: '#1e293b',
  text: '#f8fafc',
  muted: '#94a3b8',
  dim: '#64748b',
  primary: '#0ea5e9',
  white: '#ffffff',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.bg },
  container: { flex: 1, backgroundColor: colors.bg },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingText: { color: '#cbd5e1', fontSize: 16 },
  headerBrand: { color: colors.text, fontSize: 24, fontWeight: '800' },
  headerSubtitle: { color: colors.muted, fontSize: 12 },
  screenContent: { paddingHorizontal: 18, paddingBottom: 120, paddingTop: 16, gap: 14 },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', gap: 12 },
  sectionHeaderCopy: { flex: 1, gap: 4 },
  sectionEyebrow: { color: '#38bdf8', textTransform: 'uppercase', letterSpacing: 1.2, fontWeight: '800', fontSize: 11 },
  sectionBody: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  sectionBadge: { backgroundColor: '#082f49', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: '#0c4a6e' },
  sectionBadgeText: { color: '#bae6fd', fontWeight: '800', fontSize: 11, textTransform: 'uppercase' },
  heroCard: { backgroundColor: colors.card, borderRadius: 28, padding: 22, borderWidth: 1, borderColor: colors.border, gap: 12 },
  heroEyebrow: { color: '#38bdf8', textTransform: 'uppercase', letterSpacing: 1, fontWeight: '800', fontSize: 12 },
  heroTitle: { color: colors.text, fontSize: 30, fontWeight: '900', lineHeight: 36 },
  heroBody: { color: '#cbd5e1', fontSize: 15, lineHeight: 22 },
  heroButtonRow: { flexDirection: 'row', gap: 10, marginTop: 8 },
  statsRow: { flexDirection: 'row', gap: 10, marginTop: 10 },
  statCard: { flex: 1, backgroundColor: '#081120', borderRadius: 18, borderWidth: 1, borderColor: '#1e293b', padding: 14, gap: 4 },
  statValue: { color: colors.text, fontWeight: '900', fontSize: 20 },
  statLabel: { color: colors.muted, fontSize: 12 },
  primaryButton: { backgroundColor: colors.primary, paddingHorizontal: 18, paddingVertical: 14, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  primaryButtonText: { color: colors.white, fontWeight: '800', fontSize: 15 },
  secondaryButton: { borderWidth: 1, borderColor: '#334155', paddingHorizontal: 18, paddingVertical: 14, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  secondaryButtonText: { color: '#e2e8f0', fontWeight: '800', fontSize: 15 },
  sectionTitle: { color: colors.text, fontWeight: '800', fontSize: 22, marginTop: 8 },
  horizontalStrip: { marginTop: 4 },
  chip: { backgroundColor: colors.card, borderRadius: 999, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, paddingVertical: 10, marginRight: 8 },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { color: '#cbd5e1', fontWeight: '700', fontSize: 13 },
  chipTextActive: { color: colors.white },
  favoriteButton: { width: 42, height: 42, borderRadius: 999, backgroundColor: 'rgba(2, 8, 23, 0.82)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#334155' },
  favoriteButtonActive: { backgroundColor: '#7f1d1d', borderColor: '#ef4444' },
  favoriteButtonText: { color: colors.white, fontSize: 18 },
  input: { backgroundColor: colors.card, borderRadius: 18, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 16, paddingVertical: 14, color: colors.text, fontSize: 15 },
  multilineInput: { minHeight: 110, textAlignVertical: 'top' },
  card: { backgroundColor: colors.card, borderRadius: 24, overflow: 'hidden', borderWidth: 1, borderColor: colors.border, marginTop: 12 },
  cardImage: { width: '100%', height: 180, backgroundColor: '#111827' },
  cardImageWrap: { position: 'relative' },
  imageCountBadge: { position: 'absolute', right: 12, bottom: 12, backgroundColor: 'rgba(2, 8, 23, 0.82)', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: '#334155' },
  cardTopActions: { position: 'absolute', top: 12, right: 12, flexDirection: 'row', gap: 8 },
  imageCountBadgeText: { color: colors.white, fontWeight: '700', fontSize: 12 },
  cardContent: { padding: 16, gap: 8 },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  cardCategory: { color: '#38bdf8', fontWeight: '800', fontSize: 12 },
  trustRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  trustPill: { backgroundColor: '#081120', borderWidth: 1, borderColor: '#1e293b', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  trustPillText: { color: '#cbd5e1', fontSize: 11, fontWeight: '700' },
  cardPrice: { color: colors.text, fontWeight: '900', fontSize: 16 },
  cardTitle: { color: colors.text, fontWeight: '800', fontSize: 18 },
  cardMeta: { color: colors.muted, fontSize: 13 },
  cardDescription: { color: '#cbd5e1', fontSize: 14, lineHeight: 20 },
  cardSeller: { color: '#e2e8f0', fontWeight: '700', fontSize: 13 },
  cardDate: { color: colors.dim, fontSize: 12 },
  detailImage: { width: '100%', height: 260, borderRadius: 26, backgroundColor: '#111827' },
  detailThumbRow: { marginTop: 12 },
  detailThumb: { width: 78, height: 78, borderRadius: 16, marginRight: 10, borderWidth: 1, borderColor: '#1e293b', backgroundColor: '#111827' },
  detailCategory: { color: '#38bdf8', fontWeight: '800', fontSize: 13, marginTop: 16 },
  detailTitle: { color: colors.text, fontWeight: '900', fontSize: 28, lineHeight: 34, marginTop: 8 },
  detailPrice: { color: colors.text, fontWeight: '900', fontSize: 24, marginTop: 8 },
  detailMeta: { color: colors.muted, marginTop: 6, fontSize: 14 },
  detailBody: { color: '#cbd5e1', marginTop: 14, fontSize: 15, lineHeight: 22 },
  detailMetaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 12 },
  detailMetaPill: { backgroundColor: '#081120', borderRadius: 999, borderWidth: 1, borderColor: '#1e293b', paddingHorizontal: 12, paddingVertical: 8 },
  detailMetaPillText: { color: '#cbd5e1', fontWeight: '700', fontSize: 12 },
  detailInfoCard: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 22, padding: 18, marginTop: 18, gap: 4 },
  infoLabel: { color: colors.dim, textTransform: 'uppercase', fontSize: 11, fontWeight: '800', marginTop: 10 },
  infoValue: { color: colors.text, fontSize: 15 },
  noticeCard: { backgroundColor: colors.card, borderRadius: 24, borderWidth: 1, borderColor: '#334155', padding: 18, marginTop: 8 },
  noticeTitle: { color: colors.text, fontWeight: '800', fontSize: 18 },
  noticeBody: { color: '#cbd5e1', lineHeight: 22, marginTop: 8 },
  fieldLabel: { color: '#cbd5e1', fontWeight: '700', marginTop: 6 },
  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  categoryChoice: { backgroundColor: colors.card, borderRadius: 16, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, paddingVertical: 12 },
  categoryChoiceActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  categoryChoiceText: { color: '#cbd5e1', fontWeight: '700' },
  categoryChoiceTextActive: { color: colors.white },
  profileCard: { backgroundColor: colors.card, borderRadius: 24, borderWidth: 1, borderColor: colors.border, padding: 20 },
  profileTopRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  avatarLarge: { width: 72, height: 72, borderRadius: 999, backgroundColor: '#111827' },
  profileName: { color: colors.text, fontWeight: '800', fontSize: 22 },
  profileMeta: { color: colors.muted, marginTop: 6 },
  miniStatRow: { flexDirection: 'row', gap: 10, marginTop: 16 },
  miniStatCard: { flex: 1, backgroundColor: '#081120', borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 12 },
  miniStatValue: { color: colors.text, fontWeight: '900', fontSize: 18 },
  miniStatLabel: { color: colors.muted, fontSize: 12, marginTop: 2 },
  badgeRow: { flexDirection: 'row', marginTop: 16 },
  badge: { borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  badgeVerified: { backgroundColor: '#064e3b' },
  badgePending: { backgroundColor: '#3f3f46' },
  badgeText: { color: colors.white, fontWeight: '700' },
  unreadDot: { width: 10, height: 10, borderRadius: 999, backgroundColor: '#38bdf8' },
  switchAuthText: { color: '#38bdf8', textAlign: 'center', fontWeight: '700', marginTop: 4 },
  emptyState: { backgroundColor: colors.card, borderRadius: 24, borderWidth: 1, borderColor: colors.border, padding: 22, marginTop: 12 },
  emptyTitle: { color: colors.text, fontWeight: '800', fontSize: 18 },
  emptyBody: { color: colors.muted, marginTop: 6, lineHeight: 20 },
  backButton: { alignSelf: 'flex-start', backgroundColor: colors.card, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 10, borderWidth: 1, borderColor: colors.border },
  backButtonText: { color: '#e2e8f0', fontWeight: '700' },
  imagePreview: { width: 96, height: 96, borderRadius: 16, marginRight: 10, backgroundColor: '#111827' },
  helperText: { color: colors.muted, fontSize: 12, lineHeight: 18 },
  helperCard: { backgroundColor: '#081120', borderRadius: 18, borderWidth: 1, borderColor: '#1e293b', padding: 14, gap: 6 },
  helperCardTitle: { color: colors.text, fontWeight: '800', fontSize: 14 },
  formSection: { gap: 10, marginTop: 6 },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: 6 },
  statusCard: { backgroundColor: '#081120', borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 14, gap: 6 },
  statusTitle: { color: colors.text, fontWeight: '800', fontSize: 15 },
  statusBody: { color: '#cbd5e1', lineHeight: 20, fontSize: 13 },
  sellerListingCard: { backgroundColor: '#081120', borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 14, gap: 8 },
  sellerListingTitle: { color: colors.text, fontWeight: '800', fontSize: 16 },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 6 },
  smallButton: { backgroundColor: '#0f172a', borderRadius: 999, borderWidth: 1, borderColor: '#334155', paddingHorizontal: 12, paddingVertical: 10 },
  smallButtonDanger: { backgroundColor: '#3f0b0b', borderColor: '#7f1d1d' },
  smallButtonText: { color: '#e2e8f0', fontWeight: '700', fontSize: 12 },
});
